FROM mysql:8

ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=techforge
ENV MYSQL_USER=techforge_user
ENV MYSQL_PASSWORD=your_strong_password_here

COPY update_backup.sql /docker-entrypoint-initdb.d/

